### ISSUE TITLE
Keyword does not need to be spoken when -k is 0

### ISSUE THREAD

**Issue by weetabix** [ajbogh/blather#13]
When using -k 0 , 1 ,2 (any low value) (or not using -k at all), I find I can execute the default "email" command, and any other command, without using the keyword. This issue is easily reproducible. This is with the current commit. Any advice or guidance to fix that would be appreciated.

**Comment by chapma26** [comment]
Hi @weetabix, you can change line 46 in Blather.py to
`self.continuous_listen = opts.continuous`
That worked for me.

**Comment by chapma26** [comment]
Oh, almost forgot. I also went through and set keywords to self.keywords

**Comment by chapma26** [comment]
One last change at line 225...

    if self.keywordTimeLimit > 0 and self.continuous_listen and (currentTime - self.matchTime) > self.keywordTimeLimit and len(set(self.keywords).intersection(set(words))) == 0:
		words.update(self.keywords)
	elif len(set(self.keywords).intersection(set(textWords))) > 0:
		words.update(self.keywords)

**Comment by ajbogh** [comment]
@chapma26, please issue a PR for your changes. I will be glad to accept it.

**Comment by chapma26** [comment]
Done. Thanks!

**Comment by ajbogh** [comment]
Closed with PR #14. Thanks!
