### ISSUE TITLE
Keyword not found

### ISSUE THREAD

**Issue by piegamesde** [ajbogh/blather#15]
The commands.tmp says:

    # This keyword is like "Hal", or "Jarvis", or "Computer", you must say it to activate the system.
    Hal:keyword

So I made a keyword

    Raspberry:keyword

But when I say the keyword, the console writes:

    keyword
    /bin/sh: 1: keyword: not found

**Comment by ajbogh** [comment]
Is the file you made this change in commands.conf or commands.tmp? The tmp file is an example that should be copied to commands.conf before running the app.

**Comment by piegamesde** [comment]
I installed Blather with this [this](http://hackerpublicradio.org/eps/hpr2039/debian_blather_install_script)* script, but I didn't notice it was installing Blather from another repository without this feature. I updated my files and now everything works fine.

*This repo should have an installer too, it makes it really easy for new users

**Comment by ajbogh** [comment]
That's a great idea. I haven't worked on this repo for a long time but I'm thinking I should start again, and an installer script would help a bunch with that.
