### ISSUE TITLE
Blather should detect Qt or GTK automatically

### ISSUE THREAD

**Issue by ajbogh** [ajbogh/blather#20]
In the README step 6 indicates that for GTK you should use the -g flag and for Qt you should use the -q flag. It seems like it should be able to detect the environment and choose the appropriate mode by itself.

6. run Blather.py
* for Qt GUI, run Blather.py -i q
* for Gtk GUI, run Blather.py -i g

**Comment by demurgos** [comment]
How would you detect it automatically using the environment?

**Comment by ajbogh** [comment]
That's a good question. I'm going to close this issue since the upcoming versions of Blather will remove the UI completely. Blather is better suited as a daemon like Google Assistant or Alexa anyway.
